refactoring

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -21,8 +21,15 @@ jobs:
         uses: actions/checkout@master
       - name: Install flake8
         run: pip install flake8
-      - name: Run flake8
-        uses: suo/flake8-github-action@releases/v1
-        with:
-          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
-        
+      - name: Lint with flake8
+        id: flake8
+        continue-on-error: true
+        run: |
+          flake8 . --count --max-complexity=15 --max-line-length=127 --statistics
+
+      - name: Check if 'Lint with flake8' step failed
+        if: steps.flake8.outcome != 'success'
+        run: |
+          echo "flake8 fails"
+          exit 1
+          
